### ISSUE TITLE
Comments/issues/bugs/questions on edition and merging of datasets via Pandora

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/data-tools#37]
@arunge 

For testing I selected the first two files (and first sheets) from the Pandora platform. These are named Zanadamu and AfriArch isotopic dataset.

- [x] 1) In the "Prepare" tab only the last imported dataset is listed. It should be possible to select which dataset is to be "prepared". You can add a "Select table" option as can be found in the tab "Merge"

- [x] 2) Will this also work for uploaded files and URL links? In the case of uploaded files I assume that their data is saved when a SQL query is saved? As for ULR links is there a check to see if an URL is valid? 
  -> see [answer](https://github.com/Pandora-IsoMemo/data-tools/issues/37#issuecomment-1517751816)

- [x] 3) I tested the options under the tab "Prepare" all seem to be working. However, there was a bug. I did a series of delete, rename, and split operations. I then deleted the columns that I created and return to the original table names. Nonetheless, under merge the old names were still listed. Example below.

  For instance, Ifor the table AfriArch isotopic data I had changed the name of the field ID to ID2 but then changed it back to ID as shown below.

  ![image](https://user-images.githubusercontent.com/46485054/232870763-de37726f-0f96-4a63-b12c-454e3ffcaf52.png)

  Under merge, however, one has the names of the old operations (had changed name ID to ID2, had slipt a column into fields a and b, etc)

  ![image](https://user-images.githubusercontent.com/46485054/232871248-f22fc769-671c-415a-8fec-55fe3b56d898.png)

- [x] 4) I merged Zanadamu and AfriArch by the fields Country and Site.Country. I was happily surprised that this worked well since the file was quite large. I was also able to export the data. However, when clicking again on the "Import Data" button the app crashed which is strange.

- [ ] 5) I checked the option "Join on all common columns". I tried the different "Select join operation" and always got the same result: the 288 rows from the Zanadamu dataset. I did this with the "Check command line" option visible and as I selected the different operations nothing seemed to change.

- [x] 6) For the tab "Query with SQL" change the title of "Use GPT operations" to "Use AI PEITHO data operations". Once this is selected the text below should read "AI PEITHO relies on the large language model GPT. To employ GPT operations you are required to upload your access key saved in a text file. GPT operations rely on the [rgpt3](https://github.com/ben-aaron188/rgpt3) package that handles encryption.
[Pandora & IsoMemo](https://github.com/Pandora-IsoMemo) are not responsible for handling key security. Do not share your key. GPT operations consume OpenAI credit from the account associated with the key."

- [x] 7) I tried the GPT operations and they worked but I had to have the field names between square brackets. To make this clear change this text:  "SQL query    (Please, use the table ID to name tables) "

  to 

  SQL query    (Please, use the table IDs as table names and surround field names with square brackets. See example below.) 

  Then in the SQL query example write this:

  select t1.[Zanadamu.ID] as id_test2, t1.* from t1;

**Comment by arunge** [comment]
Regarding

> 6) For the tab "Query with SQL" change the title of "Use GPT operations" to "Use AI PEITHO data operations". Once this is selected the text below should read "AI PEITHO relies on the large language model GPT. To employ GPT operations you are required to upload your access key saved in a text file. GPT operations rely on the [rgpt3](https://github.com/ben-aaron188/rgpt3) package that handles encryption.
> [Pandora & IsoMemo](https://github.com/Pandora-IsoMemo) are not responsible for handling key security. Do not share your key. GPT operations consume OpenAI credit from the account associated with the key."
> 
> 7) I tried the GPT operations and they worked but I had to have the field names between square brackets. To make this clear change this text:  "SQL query    (Please, use the table ID to name tables) "
> 
> to 
> 
>  SQL query    (Please, use the table IDs as table names and surround field names with square brackets. See example below.) 
> 
> Then in the SQL query example write this:
> 
> select t1.[Zanadamu.ID] as id_test2, t1.* from t1;

I updated the texts. The changes will be available soon, when the new version of datatools was deployed in all apps.
The other points I am checking next. Thanks for your patience!

**Comment by arunge** [comment]
Regarding

> 3) I tested the options under the tab "Prepare" all seem to be working. However, there was a bug. I did a series of delete, rename, and split operations. I then deleted the columns that I created and return to the original table names. Nonetheless, under merge the old names were still listed. Example below.
> 
> For instance, Ifor the table AfriArch isotopic data I had changed the name of the field ID to ID2 but then changed it back to ID as shown below.

Currently, in the tabs "Select" and "Prepare" changes are made on the fly:
- if one changes inputs in "Select" the Preview will be updated in immediately 
- in the tab "Prepare" only the selected file from "Select" is loaded and changes are made to this loaded file. Changes are not stored in any object, which means when selecting a different file under "Select" before pressing "Send to Merge / Query" the changes will be lost since another file is loaded.

One has to press "Send to Merge/Query" to transfer changes from "Select" or "Prepare" to the tabs "Merge" and "Query".
With this behavior I wanted to avoid to many automatic updates between the different tabs.

This also explains the behavior that you observed. When the button "Send..." is pressed the current version of the selected file (including the changes from "Prepare") will be stored in a list that is available in "Merge" and "Query...". If one returns to "Prepare", and makes some changes to a file that was already "send", than one has to press "Send..." again to transfer the changes to the tabs "Merge" and "Query". If doing so, than there will be a pop up with:
![image](https://user-images.githubusercontent.com/16759098/233626994-8c3608be-4114-4e9e-8d56-538ea0a5babe.png)
Only than the changes will be present in the tabs "Merge" and "Query".

However, this part may change when I will implement points 1. and 2.

For point 2. I will explain the ideas next.

**Comment by arunge** [comment]
Regarding

> 2) Will this also work for uploaded files and URL links? In the case of uploaded files I assume that their data is saved when a SQL query is saved? As for ULR links is there a check to see if an URL is valid?

I am thinking out loud:

The plan to store inputs of the tabs "Select", "Merge" and "Query with SQL" is not very complex:
- **"Select"**: when pressing "Send to Merge/Query" (additionally to the data itself) all inputs from "Select" can be stored into that list element that is "send" to "Merge"/"Query"
- **"Merge"**: A new button to download a query will store 
  - all inputs from "Merge", and
  - all the inputs that belong to all tables that were "send" to "Merge" / "Query".
  - When uploading all these inputs again, the data that is needed in "Merge" can be reconstructed and be displayed.
- **"Query with SQL"**: Similar to the situation in "Merge", a new button to download a query will store 
  - all the inputs that belong to all tables that were "send" to "Merge" / "Query", and
  - all inputs from "Query" (this will not contain the used API key)
  - When uploading all these inputs again, data can be reconstructed and be displayed. Possibly this will not contain the output from GPT since one will have to reload the API key to make this feature available which will reset the output of gpt3. A solution could be to unset "Use GPT operations" always when a query is uploaded, than the field "SQL query" can be updated with previously downloaded input.

How to keep changes from **"Prepare"** is a bit more complex since currently each change overwrites the selected file and inputs are reset. That means, each step (change) from prepare must be stored such that the data can be reconstructed when uploading a query. Here, it does not help to store any inputs of the tab "Prepare". The inputs (and the operation) must be stored when one of the buttons "Set", "Join", "Split" or "Delete" is pressed, and the order of changes must be kept, that means we store the history of changes. When pressing "Send to Merge/Query" 
- all these information must be stored, together with 
- the object that was selected in "Select", and
- the inputs from "Select".

Than it should be possible to reconstruct the query when uploading the whole history without the data itself.

This is the plan.

**Comment by arunge** [comment]
Point 4., the crash of the app, I have not checked yet.

**Comment by arunge** [comment]
@isomemo regarding:

> However, when clicking again on the "Import Data" button the app crashed which is strange.

from [above](https://github.com/Pandora-IsoMemo/data-tools/issues/37#issue-1678334288). The reset of some value was not working correctly when the import module window was closing, thus leading to the crash when trying to import another file. This was fixed within [DataTools version 23.06.3](https://github.com/Pandora-IsoMemo/data-tools/pull/52) which is already running on ReSources beta.

I will update the other apps also when I will embed the new import module that loads model objects, see:
- https://github.com/Pandora-IsoMemo/data-tools/issues/50

**Comment by arunge** [comment]
Regarding from above:

> However, when clicking again on the "Import Data" button the app crashed which is strange.

This is fixed now on all of the app's beta versions.
